# Generated by Django 4.0.10 on 2023-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255, null=True)),
                ('internet_access', models.CharField(max_length=100, null=True)),
                ('wheelchair_accessible', models.CharField(max_length=100, null=True)),
                ('opening_hours', models.CharField(max_length=100, null=True)),
                ('grid_id', models.IntegerField()),
                ('taxi_zone', models.IntegerField()),
                ('precinct', models.IntegerField()),
                ('b_score', models.JSONField()),
                ('c_score', models.JSONField(null=True)),
                ('rating', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(default='missing', max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('password', models.CharField(default='missing', max_length=30, verbose_name='Password')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.CharField(max_length=30, verbose_name='Parks')),
                ('library', models.CharField(max_length=30, verbose_name='Libraries')),
                ('worship', models.CharField(max_length=30, verbose_name='Places of Worship')),
                ('community', models.CharField(max_length=30, verbose_name='Community Centres')),
                ('museum', models.CharField(max_length=30, verbose_name='Museums & Art Galleries')),
                ('walking_node', models.CharField(max_length=30, verbose_name='Other Walking Nodes')),
                ('park_node', models.CharField(max_length=30, verbose_name='Other Park Nodes')),
            ],
        ),
    ]
