# Generated by Django 4.2.2 on 2023-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=30, verbose_name='Longitude')),
                ('distance', models.CharField(max_length=30, verbose_name='Distance')),
            ],
        ),
    ]
