# Generated by Django 4.0.10 on 2023-07-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='park',
            field=models.CharField(max_length=30, verbose_name='Parkss'),
        ),
    ]
