# Generated by Django 4.0.10 on 2023-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userpreferences_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='park',
            field=models.CharField(max_length=30, verbose_name='Parks'),
        ),
    ]
