# Generated by Django 4.2.2 on 2023-07-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
