# Generated by Django 4.0.10 on 2023-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userroute_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('internet_access', models.CharField(max_length=100, null=True)),
                ('wheelchair_accessible', models.CharField(max_length=100, null=True)),
                ('opening_hours', models.CharField(max_length=100, null=True)),
                ('grid_id', models.IntegerField()),
                ('taxi_zone', models.IntegerField()),
                ('precinct', models.IntegerField()),
                ('b_score', models.JSONField()),
                ('c_score', models.JSONField(null=True)),
                ('rating', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
