# Generated by Django 4.0.10 on 2023-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
