# Generated by Django 4.0.10 on 2023-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_nodes_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
