# Generated by Django 4.0.10 on 2023-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_nodes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.CharField(max_length=30, verbose_name='First Name')),
                ('library', models.CharField(max_length=30, verbose_name='First Name')),
                ('worship', models.CharField(max_length=30, verbose_name='First Name')),
                ('community', models.CharField(max_length=30, verbose_name='First Name')),
                ('museum', models.CharField(max_length=30, verbose_name='First Name')),
                ('walking_node', models.CharField(max_length=30, verbose_name='First Name')),
                ('park_node', models.CharField(max_length=30, verbose_name='First Name')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRoute',
        ),
    ]
