# Generated by Django 4.0.10 on 2023-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userpreferences_delete_userroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='community',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='library',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='museum',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='park',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='park_node',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='walking_node',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='worship',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
    ]
