# Generated by Django 4.0.10 on 2023-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userpreferences_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='community',
            field=models.CharField(max_length=30, null=True, verbose_name='Community Centres'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='library',
            field=models.CharField(max_length=30, null=True, verbose_name='Libraries'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='museum',
            field=models.CharField(max_length=30, null=True, verbose_name='Museums & Art Galleries'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='park',
            field=models.CharField(max_length=30, null=True, verbose_name='Parks'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='park_node',
            field=models.CharField(max_length=30, null=True, verbose_name='Other Park Nodes'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='walking_node',
            field=models.CharField(max_length=30, null=True, verbose_name='Other Walking Nodes'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='worship',
            field=models.CharField(max_length=30, null=True, verbose_name='Places of Worship'),
        ),
    ]
