# Generated by Django 4.2.2 on 2023-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadapp', '0002_remove_records_time_alter_records_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='percipitation',
            field=models.FloatField(),
        ),
    ]
