# Generated by Django 4.2.2 on 2023-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadapp', '0003_alter_records_percipitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='time',
            field=models.CharField(default='No value', max_length=100),
        ),
    ]
